export const COLORS = {
    bg: "#0f1117",
    panel: "#1a1d2e",
    border: "#7c3aed",
    borderDim: "#2e3150",
    cyan: "#38bdf8",
    magenta: "#a78bfa",
    yellow: "#fbbf24",
    green: "#34d399",
    red: "#f87171",
    orange: "#fb923c",
    text: "#e2e8f0",
    muted: "#64748b",
};

export const S = {
    app: {
        minHeight: "100vh",
        background: COLORS.bg,
        color: COLORS.text,
        fontFamily: "'Courier New', Courier, monospace",
        backgroundImage: "repeating-linear-gradient(0deg, transparent, transparent 2px, rgba(255,0,255,0.015) 2px, rgba(255,0,255,0.015) 4px)",
    },
    nav: {
        background: COLORS.panel,
        borderBottom: `2px solid ${COLORS.magenta}`,
        padding: "0 2rem",
        display: "flex",
        alignItems: "center",
        gap: "0.5rem",
        height: "64px",
        boxShadow: `0 0 20px ${COLORS.magenta}55`,
        position: "relative",
        zIndex: 10,
    },
    logo: {
        color: COLORS.yellow,
        fontWeight: 900,
        fontSize: "1.1rem",
        letterSpacing: "0.1em",
        cursor: "pointer",
        textShadow: `0 0 10px ${COLORS.yellow}, 0 0 20px ${COLORS.yellow}88`,
        textTransform: "uppercase",
        marginRight: "1rem",
    },
    navBtn: (active) => ({
        background: active ? COLORS.magenta : "transparent",
        color: active ? COLORS.bg : COLORS.muted,
        border: `1px solid ${active ? COLORS.magenta : COLORS.borderDim}`,
        padding: "0.35rem 1rem",
        cursor: "pointer",
        fontFamily: "'Courier New', monospace",
        fontWeight: 700,
        fontSize: "0.8rem",
        letterSpacing: "0.1em",
        textTransform: "uppercase",
        boxShadow: active ? `0 0 12px ${COLORS.magenta}` : "none",
        transition: "all 0.15s",
    }),
    navRight: { marginLeft: "auto", display: "flex", gap: "0.75rem", alignItems: "center" },
    main: { padding: "2rem", maxWidth: "1100px", margin: "0 auto" },
    heading: {
        fontSize: "1.4rem",
        fontWeight: 900,
        color: COLORS.cyan,
        marginBottom: "1.5rem",
        textTransform: "uppercase",
        letterSpacing: "0.15em",
        textShadow: `0 0 10px ${COLORS.cyan}`,
        borderBottom: `1px solid ${COLORS.borderDim}`,
        paddingBottom: "0.75rem",
    },
    card: {
        background: COLORS.panel,
        border: `1px solid ${COLORS.borderDim}`,
        padding: "1.25rem",
        position: "relative",
        transition: "border-color 0.2s, box-shadow 0.2s",
        clipPath: "polygon(0 0, calc(100% - 12px) 0, 100% 12px, 100% 100%, 12px 100%, 0 calc(100% - 12px))",
        borderColor: COLORS.borderDim,   // add this
        boxShadow: "none",               // add this
    },
    cardHover: {
        borderColor: COLORS.cyan,
        boxShadow: `0 0 15px ${COLORS.cyan}44`,
    },
    grid: { display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(280px, 1fr))", gap: "1rem" },
    badge: (color) => ({
        background: "transparent",
        color: color,
        border: `1px solid ${color}`,
        fontSize: "0.65rem",
        padding: "0.15rem 0.5rem",
        fontFamily: "'Courier New', monospace",
        fontWeight: 700,
        letterSpacing: "0.1em",
        textTransform: "uppercase",
        boxShadow: `0 0 6px ${color}88`,
    }),
    input: {
        background: COLORS.bg,
        border: `1px solid ${COLORS.borderDim}`,
        color: COLORS.text,
        padding: "0.6rem 1rem",
        fontSize: "0.9rem",
        width: "100%",
        boxSizing: "border-box",
        fontFamily: "'Courier New', monospace",
        outline: "none",
        transition: "border-color 0.2s",
    },
    btn: (variant = "primary") => ({
        background: "transparent",
        color: variant === "primary" ? COLORS.magenta : variant === "danger" ? COLORS.red : variant === "success" ? COLORS.green : COLORS.muted,
        border: `1px solid ${variant === "primary" ? COLORS.magenta : variant === "danger" ? COLORS.red : variant === "success" ? COLORS.green : COLORS.borderDim}`,
        padding: "0.5rem 1.2rem",
        cursor: "pointer",
        fontFamily: "'Courier New', monospace",
        fontWeight: 700,
        fontSize: "0.8rem",
        letterSpacing: "0.1em",
        textTransform: "uppercase",
        boxShadow: variant === "primary" ? `0 0 10px ${COLORS.magenta}66` : variant === "danger" ? `0 0 10px ${COLORS.red}66` : variant === "success" ? `0 0 10px ${COLORS.green}66` : "none",
        transition: "all 0.15s",
    }),
    label: { fontSize: "0.75rem", color: COLORS.cyan, marginBottom: "0.3rem", display: "block", letterSpacing: "0.1em", textTransform: "uppercase" },
    formGroup: { marginBottom: "1rem" },
    error: { background: "#1a0010", border: `1px solid ${COLORS.red}`, color: COLORS.red, padding: "0.75rem 1rem", marginBottom: "1rem", fontSize: "0.8rem", fontFamily: "'Courier New', monospace", boxShadow: `0 0 10px ${COLORS.red}44` },
    success: { background: "#001a0d", border: `1px solid ${COLORS.green}`, color: COLORS.green, padding: "0.75rem 1rem", marginBottom: "1rem", fontSize: "0.8rem", fontFamily: "'Courier New', monospace", boxShadow: `0 0 10px ${COLORS.green}44` },
    searchBar: { display: "flex", gap: "0.75rem", marginBottom: "1.5rem" },
    tag: { background: "transparent", color: COLORS.cyan, border: `1px solid ${COLORS.borderDim}`, fontSize: "0.7rem", padding: "0.15rem 0.5rem", fontFamily: "'Courier New', monospace", letterSpacing: "0.05em" },
    modal: { position: "fixed", inset: 0, background: "rgba(0,0,0,0.85)", display: "flex", alignItems: "center", justifyContent: "center", zIndex: 100 },
    modalBox: {
        background: COLORS.panel,
        border: `1px solid ${COLORS.magenta}`,
        padding: "2rem",
        width: "100%",
        maxWidth: "460px",
        maxHeight: "90vh",
        overflowY: "auto",
        boxShadow: `0 0 40px ${COLORS.magenta}55`,
        clipPath: "polygon(0 0, calc(100% - 16px) 0, 100% 16px, 100% 100%, 16px 100%, 0 calc(100% - 16px))",
    },
    tabRow: { display: "flex", gap: "0.5rem", marginBottom: "1.5rem" },
    pixelDivider: { height: "2px", background: `linear-gradient(90deg, transparent, ${COLORS.magenta}, ${COLORS.cyan}, transparent)`, margin: "1.5rem 0", boxShadow: `0 0 8px ${COLORS.magenta}` },
};